spring:
  cloud:
    stream:
      default-binder: kafka
      bindings:
        sendToKafka-out-0:
          destination: output-topic
        getFromKafka-in-0:
          destination: output-topic
      kafka:
        binder:
          brokers: localhost:9092

  application:
    name: MoscowProject

  datasource:
    url: jdbc:postgresql://localhost:5432/moscowProjectDB
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update




  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup

#io:
#  reflectoring:
#    kafka:
#      bootstrap-servers: localhost:9092